#!/usr/bin/env bash
# Regenerates THIRD_PARTY_NOTICES.md from the modules linked into the binary
# (windows and linux builds) and saves their full license texts to
# dist/licenses/, which the release workflow zips next to the binaries. Run
# after changing go.mod; CI fails if the committed file is stale.
set -euo pipefail
export LC_ALL=C # sort the same everywhere
cd "$(dirname "$0")/.."
command -v go >/dev/null || PATH="/c/Program Files/Go/bin:$PATH" # Git Bash on Windows

# Build the tool once for this machine: GOOS set on 'go run' would build it
# for the target OS, which then cannot run here and silently reports nothing.
# GOOS set when running it selects the target build to analyse.
toolbin=$(mktemp -d)
trap 'rm -rf "$toolbin" "${tpl:-}"' EXIT
GOBIN=$toolbin go install github.com/google/go-licenses/v2@v2.0.1
golicenses=$(ls "$toolbin"/go-licenses*)
self=github.com/exomind-tmi/whatsapp-mcp
tpl=$(mktemp)
printf '{{range .}}{{.Name}}\t{{.Version}}\t{{.LicenseName}}\n{{end}}' >"$tpl"

# go-licenses exits non-zero on mere warnings (e.g. on Windows) while still
# printing the full report, so judge by the output instead.
rows=$(
  for os in windows linux; do
    GOOS=$os $golicenses report --template "$tpl" ./cmd/whatsapp-mcp 2>/dev/null || true
  done | { grep -v "^$self" || true; } | sort -u
)
if [[ -z $rows ]]; then
  echo "notices.sh: go-licenses reported no modules" >&2
  exit 1
fi
if grep -F Unknown <<<"$rows" >&2; then
  echo "notices.sh: go-licenses could not identify the licenses above" >&2
  exit 1
fi
# go-licenses names packages; the license links take their modules.
modules=$(
  for os in windows linux; do
    GOOS=$os go list -deps -f '{{with .Module}}{{.Path}}{{end}}' ./cmd/whatsapp-mcp
  done | sort -u
)

{
  cat <<'EOF'
# Third-party notices

whatsapp-mcp is licensed under GPL-3.0 (see [LICENSE](LICENSE)). The binaries also contain
the code listed below, each under its own license. Every GitHub Release ships
their full license texts as `whatsapp-mcp_<version>_licenses.zip`.

<!-- Generated by scripts/notices.sh — do not edit by hand. -->

| Component | Version | License |
|---|---|---|
| [Go standard library and runtime](https://go.dev/LICENSE) | toolchain | BSD-3-Clause |
| [SQLite](https://sqlite.org/copyright.html) (translated to Go by modernc.org/sqlite) | bundled | Public domain |
EOF
  # One row per package path, linked to the licenses of its module (the
  # longest module path prefixing it); merge the licenses of dual-licensed
  # modules.
  awk -F'\t' -v modules="$modules" '
    BEGIN { split(modules, mods, "\n") }
    function module(pkg,   i, best) {
      for (i in mods) if ((pkg == mods[i] || index(pkg, mods[i] "/") == 1) && length(mods[i]) > length(best)) best = mods[i]
      return best
    }
    {
      key = $1 FS $2
      if (!(key in lic)) { lic[key] = $3; order[++n] = key }
      else if (index(lic[key], $3) == 0) lic[key] = lic[key] " AND " $3
    }
    END {
      for (i = 1; i <= n; i++) {
        split(order[i], k, FS)
        if ((m = module(k[1])) == "") { print "notices.sh: no module for " k[1] >"/dev/stderr"; exit 1 }
        printf "| [%s](https://pkg.go.dev/%s@%s?tab=licenses) | %s | %s |\n", k[1], m, k[2], k[2], lic[order[i]]
      }
    }
  ' <<<"$rows"
} >THIRD_PARTY_NOTICES.md

rm -rf dist/licenses
# --ignore: we are GPL ourselves, and save copies the source of GPL modules, so
# it would copy the repository, dist/ included, into dist/ without end.
for os in windows linux; do
  GOOS=$os $golicenses save ./cmd/whatsapp-mcp --save_path "dist/licenses-$os" --ignore "$self" --force 2>/dev/null || true
done
mkdir -p dist/licenses/golang.org/go
for d in dist/licenses-windows dist/licenses-linux; do
  [[ -d $d ]] && cp -rf "$d/." dist/licenses/ # -f: go-licenses saves read-only files
done
if [[ ! -d dist/licenses/modernc.org ]]; then
  echo "notices.sh: go-licenses saved no license texts" >&2
  exit 1
fi
cp "$(go env GOROOT)/LICENSE" dist/licenses/golang.org/go/LICENSE # stdlib and runtime
rm -rf dist/licenses-windows dist/licenses-linux dist/licenses/"$self"
echo "THIRD_PARTY_NOTICES.md: $(grep -c '^| \[' THIRD_PARTY_NOTICES.md) components; texts in dist/licenses/"
