#!/usr/bin/env bash
# Regenerates THIRD_PARTY_NOTICES.md from the modules linked into the binary
# (windows and linux builds) and saves their full license texts to
# dist/licenses/ for packaging next to the binaries. Run after changing go.mod;
# CI fails if the committed file is stale.
set -euo pipefail
cd "$(dirname "$0")/.."
command -v go >/dev/null || PATH="/c/Program Files/Go/bin:$PATH" # Git Bash on Windows

golicenses="go run github.com/google/go-licenses/v2@v2.0.1"
self=github.com/exomind-tmi/whatsapp-mcp
tpl=$(mktemp)
trap 'rm -f "$tpl"' EXIT
printf '{{range .}}{{.Name}}\t{{.Version}}\t{{.LicenseName}}\t{{.LicenseURL}}\n{{end}}' >"$tpl"

# go-licenses exits non-zero on mere warnings (e.g. on Windows) while still
# printing the full report, so judge by the output instead.
rows=$(
  for os in windows linux; do
    GOOS=$os $golicenses report --template "$tpl" ./cmd/whatsapp-mcp 2>/dev/null || true
  done | { grep -v "^$self" || true; } | sort -u
)
if [[ -z $rows ]]; then
  echo "notices.sh: go-licenses reported no modules" >&2
  exit 1
fi

{
  cat <<'EOF'
# Third-party notices

whatsapp-mcp is MIT-licensed (see [LICENSE](LICENSE)). The binaries also contain
the code listed below, each under its own license. Full license texts ship with
every release in the `licenses/` folder.

<!-- Generated by scripts/notices.sh — do not edit by hand. -->

| Component | Version | License |
|---|---|---|
| [Go standard library and runtime](https://go.dev/LICENSE) | toolchain | BSD-3-Clause |
| [SQLite](https://sqlite.org/copyright.html) (translated to Go by modernc.org/sqlite) | bundled | Public domain |
EOF
  # One row per package path; merge the licenses of dual-licensed modules.
  awk -F'\t' '
    { key = $1 FS $2; lic[key] = (key in lic && index(lic[key], $3) == 0) ? lic[key] " AND " $3 : (key in lic ? lic[key] : $3); url[key] = $4; if (!(key in seen)) { seen[key] = 1; order[++n] = key } }
    END { for (i = 1; i <= n; i++) { split(order[i], k, FS); printf "| [%s](%s) | %s | %s |\n", k[1], url[order[i]], k[2], lic[order[i]] } }
  ' <<<"$rows"
} >THIRD_PARTY_NOTICES.md

rm -rf dist/licenses
for os in windows linux; do
  GOOS=$os $golicenses save ./cmd/whatsapp-mcp --save_path "dist/licenses-$os" --force 2>/dev/null || true
done
mkdir -p dist/licenses/golang.org/go
for d in dist/licenses-windows dist/licenses-linux; do
  [[ -d $d ]] && cp -r "$d/." dist/licenses/
done
if [[ ! -d dist/licenses/modernc.org ]]; then
  echo "notices.sh: go-licenses saved no license texts" >&2
  exit 1
fi
cp "$(go env GOROOT)/LICENSE" dist/licenses/golang.org/go/LICENSE # stdlib and runtime
rm -rf dist/licenses-windows dist/licenses-linux dist/licenses/"$self"
echo "THIRD_PARTY_NOTICES.md: $(grep -c '^| \[' THIRD_PARTY_NOTICES.md) components; texts in dist/licenses/"
